stand-alone (electron) app
personium/app-uc-unit-manager pull request #179
Opened 2021-12-01 07:49 UTC by yoh1496

To make app-uc-unit-manager can be used freely from web server,
I implemented some codes to launch app-uc-unit-manager in electron.

How about this?

2021-12-02 01:26 UTC, dixonsiu approved these changes
Great job. Thank you.

2021-12-02 01:30 UTC, dixonsiu commented on main.js
> +  mainWindow.loadFile(__dirname + "/src/html/login.html");
Please put comment or add information in README that the path must be modified for Personium Cell or Electron.

2021-12-02 02:48 UTC, tochi-y requested changes
Thank you for your great work! Please check the comments.

2021-12-02 02:48 UTC, tochi-y commented on package.json
> +  "license": "ISC",
```suggestion
  "license": "Apache License 2.0",
```

2021-12-02 02:48 UTC, tochi-y commented on package.json
> +  "version": "1.0.0",
Release version needs to be considered.

2021-12-02 06:54 UTC, yoh1496 commented
@tochi-y 
I tested that `login.js` works if it is launched in Web Browser.
Could you merge this?

2021-12-09 04:29 UTC, tochi-y commented
@yoh1496 After merging #178, conflicts have occurred. Can you fix this?

2021-12-13 10:26 UTC, yoh1496 commented
I rebased and solved conflicts

2021-12-23 08:06 UTC, tochi-y commented on package.json
> +  "license": "ISC",
```suggestion
  "license": "Apache License 2.0",
```

2021-12-23 08:07 UTC, tochi-y approved these changes

2021-12-23 08:07 UTC, merged